# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Take a subset of rows and create another MTX file-set
#'
#' @param mtx_file data file
#' @param row_file row file
#' @param col_file column file
#' @param selected selected row names
#'
#'
rcpp_copy_selected_rows <- function(mtx_file, row_file, col_file, r_selected, output) {
    .Call('_mmutilR_rcpp_copy_selected_rows', PACKAGE = 'mmutilR', mtx_file, row_file, col_file, r_selected, output)
}

#' Take a subset of columns and create another MTX file-set
#'
#' @param mtx_file data file
#' @param row_file row file
#' @param col_file column file
#' @param selected selected column names
#'
rcpp_copy_selected_columns <- function(mtx_file, row_file, col_file, r_selected, output) {
    .Call('_mmutilR_rcpp_copy_selected_columns', PACKAGE = 'mmutilR', mtx_file, row_file, col_file, r_selected, output)
}

#' Create an index file for a given MTX
#'
#' @param mtx_file data file
#' @param index_file index file
#'
#' @usage rcpp_build_mmutil_index(mtx_file, index_file)
#'
#' @return EXIT_SUCCESS or EXIT_FAILURE
#'
rcpp_build_mmutil_index <- function(mtx_file, index_file = "") {
    .Call('_mmutilR_rcpp_build_mmutil_index', PACKAGE = 'mmutilR', mtx_file, index_file)
}

#' Read an index file to R
#'
#' @param index_file index file
#'
#' @return a vector column index (a vector of memory locations)
#'
rcpp_read_mmutil_index <- function(index_file) {
    .Call('_mmutilR_rcpp_read_mmutil_index', PACKAGE = 'mmutilR', index_file)
}

#' Check if the index tab is valid
#'
#' @param mtx_file data file
#' @param index_tab index tab (a vector of memory locations)
#'
#' @return EXIT_SUCCESS or EXIT_FAILURE
#'
rcpp_check_index_tab <- function(mtx_file, index_tab) {
    .Call('_mmutilR_rcpp_check_index_tab', PACKAGE = 'mmutilR', mtx_file, index_tab)
}

#' Read a subset of columns from the data matrix
#' @param mtx_file data file
#' @param memory_location column -> memory location
#' @param column_index column indexes to retrieve (1-based)
#'
#' @return a dense sub-matrix
#'
rcpp_read_columns <- function(mtx_file, memory_location, column_index) {
    .Call('_mmutilR_rcpp_read_columns', PACKAGE = 'mmutilR', mtx_file, memory_location, column_index)
}

